export const skillData = [
  "ReactJS",
  "Angular",
  "Vue.js",
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "Java",
  "Python",
  "C++",
  "C#",
  "PHP",
  "Ruby",
  "Swift",
  "Kotlin",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Ruby on Rails",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Firebase",
  "SQLite",
  "Git",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "RESTful API",
  "GraphQL",
  "Responsive Web Design",
  "UI/UX Design",
  "Agile Development",
  "Scrum",
  "DevOps",
  "Machine Learning",
  "Artificial Intelligence",
  "Data Science",
  "Cybersecurity",
  "Blockchain",
  "AR/VR Development",
  "Game Development",
  "Big Data",
  "Microservices",
  "Serverless Architecture",
  "Linux Administration",
];
